### ISSUE TITLE
visualization exercise issue

### ISSUE THREAD

**Issue by Weifanwu66** [Jacobmatta/jacobmatta-MADA-portfolio#3]
Great job overall! I forked your work and I had a few things changed in this exercise as follows:
1.  Adding `coord_fixed(ratio=1, xlim=c(-10,10),ylim=c(-10,10))` after labs ( ) function. It makes the graph more proportional in my opinion.
2.  In the theme ( ) function, adding `panel.bacground=element_rect(fill="#FFFFFF")` , `panel.grid.major=element_line(color="lightgrey") `, and `axis.ticks=element_blank ( ) `to match the background in the original graph.
3. in ggplotly ( ) function, I specify the width=550 and height=600 in order to make the graph match the original one. 
4. I modified the hoverlabel inside the layout function using layout(hoverlabel=list(bgcolor="#FFFFFF",
                         font=list(color="#888888")).
 I also tried to highlight the points with orange color with `highlight(on="plotly_hover",selected=attrs_selected(point=list(color="#FFA500",fill="#FFFFFF")))`.
 However, it didn't work for some reason, and the pink & green panels in the background and labels also disappeared on my end. I haven't figured it out yet, but I will try more sometime soon.

**Comment by Jacobmatta** [comment]
Thank you! I will attempt to make these edits. I appreciate your feedback.
