### ISSUE TITLE
some non-working bits

### ISSUE THREAD

**Issue by andreashandel** [Jacobmatta/jacobmatta-MADA-portfolio#4]
the formatting of the code in our data analysis exercise doesn't work right. the way it is written, it's not possible to run the quarto script and run the code.

often, in our quarto files, the headings are not rendered properly because you omit the needed space.

the link to your github repository on the main page also doesn't work.

**Comment by Jacobmatta** [comment]
Thank you for reporting this as an issue. I believe I have fixed the formatting issue in the data analysis exercise and I have updated my github link on the main page of my portfolio website, so it should work from now on.
