### ISSUE TITLE
flu analysis not showing

### ISSUE THREAD

**Issue by andreashandel** [Jacobmatta/jacobmatta-MADA-portfolio#5]
i can't see the flu analysis exercise on your website. looks like you don't have it in your quarto YAML.

**Comment by Jacobmatta** [comment]
I added it in my quarto YAML and pushed the changes from GitKraken. In RStudio, when I render my website the flu analysis exercise shows up but when I access my website from the link on GitHub, the flu analysis exercise does not show up and I'm unsure why. 

I will continue to try to fix this.

**Comment by Jacobmatta** [comment]
The flu analysis menu should now be visible on my website
